name: ReportGUI
version: 1.0.0
main: DerCommander610\Report\Main
api: [4.19.3]
author: DerCommander610

commands:
  report:
   descripton: "report a hacker or rule breaker"
   permission: report.cmd
permissions:
   report.cmd:
    default: true
   report.view:
    default: op      
